name: Dependabot auto-merge

on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Fetch metadata on dependabot PR
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.1
      - name: Approve dependabot PR using PAT
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Approve dependabot PR using PAT
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.PAT_TOKEN}}
          GITHUB_TOKEN: ${{secrets.PAT_TOKEN}}
      # - name: Enable auto-merge for dependabot PR
      #   run: gh pr merge --auto --squash "$PR_URL"
      #   env:
      #     PR_URL: ${{github.event.pull_request.html_url}}
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
